//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public int id { get; set; }
        public string kad { get; set; }
        public string sifre { get; set; }

        public virtual bool BeniHatirla { get; set; }
    }
}
